In [29]:
import pandas as pd
from pathlib import Path

step_1_path = Path("../Data/crawl2_files/extracted_metrics_unified.parquet")
step_2_path = Path("../Data/crawl2_files/thesis_meta_all_metrics_except_grade_and_supervisor_LEFT.parquet")
step_3_path = Path("/Users/oliver/Desktop/MSc_Speciale/ThesisDataRepo/data/crawl2/BASE_DATA_BIG.parquet")

step_1 = pd.read_parquet(step_1_path)
print(f"Rows in step_1 DataFrame: {len(step_1)}")
print(f"Unique filenames in step_1 DataFrame: {step_1['filename'].nunique()}")
step_2 = pd.read_parquet(step_2_path)
print(f"Rows in step_2 DataFrame: {len(step_2)}")
print(f"Unique filenames in step_2 DataFrame: {step_2['filename'].nunique()}")
step_3 = pd.read_parquet(step_3_path)
print(f"Rows in step_3 DataFrame: {len(step_3)}")
print(f"Unique filenames in step_3 DataFrame: {step_3['filename'].nunique()}")

Rows in step_1 DataFrame: 9889
Unique filenames in step_1 DataFrame: 9889
Rows in step_2 DataFrame: 9889
Unique filenames in step_2 DataFrame: 9889
Rows in step_3 DataFrame: 9889
Unique filenames in step_3 DataFrame: 9889

### Step 1

In [22]:
df_1 = step_1.copy()
# new column "ID" by splitting "filename" at ".txt" and taking the first part
df_1["ID"] = df_1["filename"].str.split(".txt").str[0].astype(str)
# place ID column at the second index (after filename)
cols = df_1.columns.tolist()
cols.insert(1, cols.pop(cols.index("ID")))
df_1 = df_1[cols]
display(df_1.head())

len(df_1["ID"].unique())

,filename,ID,num_tot_pages,num_cont_pages,num_words_full,num_words_cont,num_figures,num_tables,num_references,total_sentences,...,lexical_diversity,flesch_kincaid_grade,handin_month,abstract_ts,Author,num_authors,Publication Year,primary_member_id_s,Title,Department_new
0,2692305267.txt,2692305267,50,45,9398,7940,41.0,8.0,69.0,429.0,...,0.209,11.9,February 2180,None,None,NaN,NaN,None,None,None
1,2439430818.txt,2439430818,81,77,12223,11648,64.0,6.0,29.0,582.0,...,0.155,9.1,August 2018,None,None,NaN,NaN,None,None,None
2,2712810173.txt,2712810173,54,39,14897,11982,31.0,14.0,58.0,577.0,...,0.179,12.3,June 2022,None,None,NaN,NaN,None,None,None
3,2712907369.txt,2712907369,63,50,16425,14009,24.0,8.0,NaN,701.0,...,0.161,12.0,June 2022,None,None,NaN,NaN,None,None,None
4,2385162063.txt,2385162063,75,58,17712,14056,36.0,4.0,23.0,642.0,...,0.174,9.4,August 2017,None,None,NaN,NaN,None,None,None

9889

In [23]:
# a list of IDs from df_1
ids_df_1 = df_1["ID"].unique().tolist()

### Step 2

In [24]:
meta_path = Path("../Data/crawl2_files/meta_findit/meta_findit_all_merged.csv")
df_meta = pd.read_csv(meta_path, sep=";", low_memory=False)
df_meta["ID"] = df_meta["ID"].astype(str)
# drop duplicates based on ID, keeping the row with the fewest missing values
df_meta = (
    df_meta.assign(_na_count=df_meta.isna().sum(axis=1))
    .sort_values(by="_na_count")
    .drop(columns="_na_count")
    .drop_duplicates(subset=["ID"], keep="first")
    .reset_index(drop=True)
)
print(f"Rows in meta DataFrame: {len(df_meta)}")
print(f"Unique IDs in meta DataFrame: {df_meta['ID'].nunique()}")

Rows in meta DataFrame: 15414
Unique IDs in meta DataFrame: 15414

In [25]:
df_meta

,abstract_ts,access_ss,Affiliations,Timestamp,Author,citation_count_i,ID,dtu_library_collection_facet,collection_facet,Publication Year,...,keywords_facet,keywords_normalized,isolanguage_facet,member_id_ss,ORCID,primary_member_id_s,Publisher,Source,source_all_ss,Title
0,The aim of this Master's thesis study was to d...,dtu|dtupub,VTT (former employee or external),2022-03-28T07:11:47.509Z,"Tiitinen, Jutta",NaN,2708546053,NaN,dtu,2014,...,cellulose acetate|fouling|membrane modificatio...,cellulose acetate|fouling|membrane modificatio...,eng,6231fa02466824b6f30e0d93,NaN,6231fa02466824b6f30e0d93,VTT Technical Research Centre of Finland,vtt,vtt,Membrane development for oil contaminated wate...
1,"In this thesis, the applicability of the homog...",dtu|dtupub,BA2703 Ship and arctic technology,2022-03-28T07:08:53.875Z,"Viitanen, Ville",NaN,2708546057,NaN,dtu,2015,...,CFD|FINFLO|SDG 14 - Life Below Water|VOF|YAFFA...,CFD|FINFLO|SDG 14 - Life Below Water|VOF|YAFFA...,eng,6231fa022b9a3ab6f3999b0f,NaN,6231fa022b9a3ab6f3999b0f,VTT Technical Research Centre of Finland,vtt,vtt,Verification of a homogeneous micture model fo...
2,"In this research, the objective is to find out...",dtu|dtupub,VTT (former employee or external),2022-03-28T07:13:32.391Z,"Muhonen, Tiia",NaN,2708546398,NaN,dtu,2015,...,Internet of Things|M2M|condition-based mainten...,Internet of Things|M2M|condition-based mainten...,eng,6231fa07579319b6f3fae4f5,NaN,6231fa07579319b6f3fae4f5,University of Oulu,vtt,vtt,Standardization of industrial internet and IoT...
3,Measuring and analysing the quality of experie...,dtu|dtupub,VTT (former employee or external),2022-03-28T07:10:58.994Z,"Ruottinen, Pekka",NaN,2708546311,NaN,dtu,2015,...,DBMS|MySQL|database|optimization|qosmet|qualit...,DBMS|MySQL|database|optimization|qosmet|qualit...,eng,6231fa054eee74b6f3f60568,NaN,6231fa054eee74b6f3f60568,University of Oulu,vtt,vtt,Database architecture design and performance e...
4,CSP hybrids are one of the possible technical ...,dtu|dtupub,BA3601 Renewable Energy Processes,2022-03-28T07:11:52.979Z,"Suojanen, Suvi",NaN,2708546273,NaN,dtu,2016,...,Apros|SDG 7 - Affordable and Clean Energy|conc...,Apros|SDG 7 - Affordable and Clean Energy|conc...,eng,6231fa05662e01b6f37c0898,NaN,6231fa05662e01b6f37c0898,Tampere University of Technology,vtt,vtt,Development of Concentrated Solar Power and Co...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15409,NaN,dtu|dtupub|third_party,NaN,2024-03-08T01:15:57.464Z,"Pal, Amartyadeep",NaN,2734221818,NaN,dtu,2024,...,NaN,NaN,und,65ea6552d189d417b6243abc,NaN,65ea6552d189d417b6243abc,DTU Department of Wind and Energy Systems,sorbit,sorbit,Techno-economic analysis for repowering legacy...
15410,NaN,dtu|dtupub|third_party,NaN,2024-03-05T02:02:28.117Z,"Carmona, Javiera Laing",NaN,2734125238,NaN,dtu,2024,...,NaN,NaN,und,65e670dadd12473f799b735b,NaN,65e670dadd12473f799b735b,DTU Department of Applied Mathematics and Comp...,sorbit,sorbit,Using autoencoders for delineation of childhoo...
15411,NaN,dtu|dtupub|third_party,NaN,2024-10-11T00:09:42.913Z,"Drygaard, Benedicte Bruus Michaelsen",NaN,2739656849,NaN,dtu,2024,...,NaN,NaN,und,67086cc68e760043d9426312,NaN,67086cc68e760043d9426312,DTU Department of Biotechnology and Biomedicine,sorbit,sorbit,Genetic tools for construction of multi-specie...
15412,NaN,dtu|dtupub|third_party,NaN,2024-04-01T00:10:04.182Z,"Jørgensen, Jonas Dalsberg",NaN,2735269676,NaN,dtu,2024,...,NaN,NaN,und,6609fb5ba78eff1e2ed10db3,NaN,6609fb5ba78eff1e2ed10db3,DTU Department of Biotechnology and Biomedicine,sorbit,sorbit,Inter-study variation of SomaScan platform|Int...
15413,NaN,dtu|dtupub|third_party,NaN,2022-01-03T13:13:11.234Z,"Abdulrahman, Tareq",NaN,2390476037,NaN,dtu,2017,...,NaN,NaN,und,59cb87a55010df231c4b9ebd,NaN,59cb87a55010df231c4b9ebd,DTU Department of Chemical and Biochemical Eng...,sorbit,sorbit,Ignition of biomass in power plant mills|Antæn...

In [26]:
# how many of the ids_df_1 are in df_meta
ids_in_meta = df_meta[df_meta["ID"].isin(ids_df_1)]
print(f"IDs from df_1 that are in meta DataFrame: {len(ids_in_meta)}")
print(f"Unique IDs from df_1 that are in meta DataFrame: {ids_in_meta['ID'].nunique()}")

# list all the missing IDs from df_1 that are not in meta DataFrame
missing_ids = set(ids_df_1) - set(df_meta["ID"])
print(f"IDs from df_1 that are NOT in meta DataFrame: {len(missing_ids)}")

# new df for only the missing_ids
df_missing = df_1[df_1["ID"].isin(missing_ids)]
#df_missing.info()
# display df_missing for colums: "filename","ID","Publication Year","Title"
#display(df_missing[["filename", "ID", "Publication Year", "Title"]])
export_df = df_missing[["filename", "ID"]]
#unique IDs in export_df
export_df.to_csv("/Users/oliver/Downloads/missing_ids_from_meta.csv", sep=";",index=False)

IDs from df_1 that are in meta DataFrame: 9618
Unique IDs from df_1 that are in meta DataFrame: 9618
IDs from df_1 that are NOT in meta DataFrame: 271

In [27]:
df_union = pd.merge(df_1[["filename", "ID"]], df_meta[["ID"]], on="ID", how="inner", suffixes=("_metrics", "_meta"))
# Showing the dataframe in a simple way to check the merge result with only the IDs and filenames from both dataframes
display(df_union)

print(f"Rows in union DataFrame: {len(df_union)}")
print(f"Unique IDs in union DataFrame: {df_union['ID'].nunique()}")

            filename          ID
0     2692305267.txt  2692305267
1     2439430818.txt  2439430818
2     2712810173.txt  2712810173
3     2712907369.txt  2712907369
4     2385162063.txt  2385162063
...              ...         ...
9613  2709902274.txt  2709902274
9614  2451029150.txt  2451029150
9615  2497546697.txt  2497546697
9616  2692890879.txt  2692890879
9617  2737702132.txt  2737702132

[9618 rows x 2 columns]

Rows in union DataFrame: 9618
Unique IDs in union DataFrame: 9618

In [28]:
df_2 = step_2.copy()
# new column "ID" by splitting "filename" at ".txt" and taking the first part
#df_2["ID"] = df_2["filename"].str.split(".txt").str[0]
# place ID column at the second index (after filename)
# cols = df_2.columns.tolist()
# cols.insert(1, cols.pop(cols.index("ID")))
# df_2 = df_2[cols]
display(df_2)

len(df_2["ID"].unique())

,filename,num_tot_pages,num_cont_pages,num_words_full,num_words_cont,num_figures,num_tables,num_references,total_sentences,total_words,...,flesch_kincaid_grade,handin_month,abstract_ts,Author,num_authors,Publication Year,primary_member_id_s,Title,Department_new,ID
0,2692305267.txt,50,45,9398,7940,41.0,8.0,69.0,429.0,8168.0,...,11.9,February 2180,NaN,"Jiang, Qi",1.0,2021.0,61110d1ad9001d016215791c,Growth of Lactococcus lactis and microbial met...,DTU Food,2692305267
1,2439430818.txt,81,77,12223,11648,64.0,6.0,29.0,582.0,9342.0,...,9.1,August 2018,NaN,"Venkata, Pawan Krishna Mohan Rao Sriperumbuduri",1.0,2018.0,5ba4d1d3d9001d01b30b153d,Design and Analysis of a 300 GHz Integrated Po...,DTU Electro,2439430818
2,2712810173.txt,54,39,14897,11982,31.0,14.0,58.0,577.0,10988.0,...,12.3,June 2022,NaN,"Tomulic, Petra",1.0,2022.0,62dddf6ea0492e54e4cb319f,Bestemmelse af bionedbrydningskinetik for esse...,DTU Sustain,2712810173
3,2712907369.txt,63,50,16425,14009,24.0,8.0,NaN,701.0,14379.0,...,12.0,June 2022,NaN,"Jørgensen, Lucas Rebien",1.0,2022.0,62e5c84932d573a44628047a,New analytical method for direct determination...,DTU Health Tech,2712907369
4,2385162063.txt,75,58,17712,14056,36.0,4.0,23.0,642.0,11983.0,...,9.4,August 2017,NaN,"Montero, Mariana Montenegro",1.0,2017.0,59b7bf685010df28b56065bc,Optimization of cyclic pitch control for a ver...,DTU Wind,2385162063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9884,2451029150.txt,75,57,21279,18777,54.0,10.0,62.0,905.0,16533.0,...,11.2,May 2019,NaN,"Moolman, Johannes",1.0,2019.0,5d3d8417d9001d32f558c327,Operating a hybrid power plant in the Australi...,DTU Wind,2451029150
9885,2497546697.txt,59,44,13323,12190,29.0,7.0,NaN,596.0,12368.0,...,12.5,February 2020,NaN,"Muchena, Chenai Elizabeth",1.0,2020.0,5e60ec9fd9001d016338acd5,Secondary metabolites from Streptomyces iranen...,DTU Bioengineering,2497546697
9886,2692890879.txt,47,45,14097,14071,38.0,0.0,14.0,620.0,12793.0,...,11.1,July 2021,NaN,"Thapa, Umesh Saru",1.0,2021.0,6120df23d9001d0478369047,Evaluation of Outdoor Electroluminescence Imag...,DTU Electro,2692890879
9887,2728315454.txt,50,47,11707,11568,25.0,2.0,28.0,603.0,11239.0,...,11.6,December 4292,NaN,"Sabadin, Matteo",1.0,2023.0,65024f36a063b61200008a4b,Detection of waste disposal sites from satelli...,DTU Management,2728315454
9888,2737702132.txt,88,75,31006,28025,47.0,17.0,46.0,1518.0,27455.0,...,10.6,June 2024,NaN,"Rasmussen, Kasper Juul Hesse",1.0,2024.0,669da344dd1c90e8f3f97411,Analysis and hardware implementation of compre...,DTU Compute,2737702132

9889