In [1]:
import pandas as pd
from pathlib import Path

step_1_path = Path("../Data/crawl2_files/extracted_metrics_unified.parquet")
step_2_path = Path("../Data/crawl2_files/thesis_meta_all_metrics_except_grade_and_supervisor_LEFT.parquet")
step_3_path = Path("/Users/oliver/Desktop/MSc_Speciale/ThesisDataRepo/data/crawl2/BASE_DATA_BIG.parquet")

step_1 = pd.read_parquet(step_1_path)
print(f"Rows in step_1 DataFrame: {len(step_1)}")
print(f"Unique filenames in step_1 DataFrame: {step_1['filename'].nunique()}")
step_2 = pd.read_parquet(step_2_path)
print(f"Rows in step_2 DataFrame: {len(step_2)}")
print(f"Unique filenames in step_2 DataFrame: {step_2['filename'].nunique()}")
step_3 = pd.read_parquet(step_3_path)
print(f"Rows in step_3 DataFrame: {len(step_3)}")
print(f"Unique filenames in step_3 DataFrame: {step_3['filename'].nunique()}")

Rows in step_1 DataFrame: 9889
Unique filenames in step_1 DataFrame: 9889
Rows in step_2 DataFrame: 9889
Unique filenames in step_2 DataFrame: 9889
Rows in step_3 DataFrame: 9619
Unique filenames in step_3 DataFrame: 9619

### Step 1

In [39]:
df_1 = step_1.copy()
# new column "ID" by splitting "filename" at ".txt" and taking the first part
df_1["ID"] = df_1["filename"].str.split(".txt").str[0].astype(str)
# place ID column at the second index (after filename)
cols = df_1.columns.tolist()
cols.insert(1, cols.pop(cols.index("ID")))
df_1 = df_1[cols]
display(df_1.head())

len(df_1["ID"].unique())

,filename,ID,num_tot_pages,num_cont_pages,num_words_full,num_words_cont,num_figures,num_tables,num_references,total_sentences,...,lexical_diversity,flesch_kincaid_grade,handin_month,abstract_ts,Author,num_authors,Publication Year,primary_member_id_s,Title,Department_new
0,2692305267.txt,2692305267,50,45,9398,7940,41.0,8.0,69.0,429.0,...,0.209,11.9,February 2180,None,None,NaN,NaN,None,None,None
1,2439430818.txt,2439430818,81,77,12223,11648,64.0,6.0,29.0,582.0,...,0.155,9.1,August 2018,None,None,NaN,NaN,None,None,None
2,2712810173.txt,2712810173,54,39,14897,11982,31.0,14.0,58.0,577.0,...,0.179,12.3,June 2022,None,None,NaN,NaN,None,None,None
3,2712907369.txt,2712907369,63,50,16425,14009,24.0,8.0,NaN,701.0,...,0.161,12.0,June 2022,None,None,NaN,NaN,None,None,None
4,2385162063.txt,2385162063,75,58,17712,14056,36.0,4.0,23.0,642.0,...,0.174,9.4,August 2017,None,None,NaN,NaN,None,None,None

9889

### Step 2

In [44]:
meta_path = Path("../Data/crawl2_files/meta_findit/meta_findit_all_merged.csv")
df_meta = pd.read_csv(meta_path,sep=";", low_memory=False)
df_meta["ID"] = df_meta["ID"].astype(str)
print(f"Rows in meta DataFrame: {len(df_meta)}")
print(f"Unique IDs in meta DataFrame: {df_meta['ID'].nunique()}")

Rows in meta DataFrame: 30961
Unique IDs in meta DataFrame: 15414

In [ ]:
df_union = pd.merge(df_1[["filename", "ID"]], df_meta[["ID"]], on="ID", how="inner", suffixes=("_metrics", "_meta"))
# Showing the dataframe in a simple way to check the merge result with only the IDs and filenames from both dataframes
display(df_union)

print(f"Rows in union DataFrame: {len(df_union)}")
print(f"Unique IDs in union DataFrame: {df_union['ID'].nunique()}")

             filename          ID
0      2692305267.txt  2692305267
1      2692305267.txt  2692305267
2      2439430818.txt  2439430818
3      2439430818.txt  2439430818
4      2712810173.txt  2712810173
...               ...         ...
19823  2692890879.txt  2692890879
19824  2692890879.txt  2692890879
19825  2737702132.txt  2737702132
19826  2737702132.txt  2737702132
19827  2737702132.txt  2737702132

[19828 rows x 2 columns]

Rows in union DataFrame: 19828
Unique IDs in union DataFrame: 9618

In [14]:
df_2 = step_2.copy()
# new column "ID" by splitting "filename" at ".txt" and taking the first part
#df_2["ID"] = df_2["filename"].str.split(".txt").str[0]
# place ID column at the second index (after filename)
# cols = df_2.columns.tolist()
# cols.insert(1, cols.pop(cols.index("ID")))
# df_2 = df_2[cols]
display(df_2)

len(df_2["ID"].unique())

,filename,num_tot_pages,num_cont_pages,num_words_full,num_words_cont,num_figures,num_tables,num_references,total_sentences,total_words,...,flesch_kincaid_grade,handin_month,abstract_ts,Author,num_authors,Publication Year,primary_member_id_s,Title,Department_new,ID
0,2692305267.txt,50,45,9398,7940,41.0,8.0,69.0,429.0,8168.0,...,11.9,February 2180,NaN,"Jiang, Qi",1.0,2021.0,61110d1ad9001d016215791c,Growth of Lactococcus lactis and microbial met...,DTU Food,2692305267
1,2439430818.txt,81,77,12223,11648,64.0,6.0,29.0,582.0,9342.0,...,9.1,August 2018,NaN,"Venkata, Pawan Krishna Mohan Rao Sriperumbuduri",1.0,2018.0,5ba4d1d3d9001d01b30b153d,Design and Analysis of a 300 GHz Integrated Po...,DTU Electro,2439430818
2,2712810173.txt,54,39,14897,11982,31.0,14.0,58.0,577.0,10988.0,...,12.3,June 2022,NaN,"Tomulic, Petra",1.0,2022.0,62dddf6ea0492e54e4cb319f,Bestemmelse af bionedbrydningskinetik for esse...,DTU Sustain,2712810173
3,2712907369.txt,63,50,16425,14009,24.0,8.0,NaN,701.0,14379.0,...,12.0,June 2022,NaN,"Jørgensen, Lucas Rebien",1.0,2022.0,62e5c84932d573a44628047a,New analytical method for direct determination...,DTU Health Tech,2712907369
4,2385162063.txt,75,58,17712,14056,36.0,4.0,23.0,642.0,11983.0,...,9.4,August 2017,NaN,"Montero, Mariana Montenegro",1.0,2017.0,59b7bf685010df28b56065bc,Optimization of cyclic pitch control for a ver...,DTU Wind,2385162063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9884,2451029150.txt,75,57,21279,18777,54.0,10.0,62.0,905.0,16533.0,...,11.2,May 2019,NaN,"Moolman, Johannes",1.0,2019.0,5d3d8417d9001d32f558c327,Operating a hybrid power plant in the Australi...,DTU Wind,2451029150
9885,2497546697.txt,59,44,13323,12190,29.0,7.0,NaN,596.0,12368.0,...,12.5,February 2020,NaN,"Muchena, Chenai Elizabeth",1.0,2020.0,5e60ec9fd9001d016338acd5,Secondary metabolites from Streptomyces iranen...,DTU Bioengineering,2497546697
9886,2692890879.txt,47,45,14097,14071,38.0,0.0,14.0,620.0,12793.0,...,11.1,July 2021,NaN,"Thapa, Umesh Saru",1.0,2021.0,6120df23d9001d0478369047,Evaluation of Outdoor Electroluminescence Imag...,DTU Electro,2692890879
9887,2728315454.txt,50,47,11707,11568,25.0,2.0,28.0,603.0,11239.0,...,11.6,December 4292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9888,2737702132.txt,88,75,31006,28025,47.0,17.0,46.0,1518.0,27455.0,...,10.6,June 2024,NaN,"Rasmussen, Kasper Juul Hesse",1.0,2024.0,669da344dd1c90e8f3f97411,Analysis and hardware implementation of compre...,DTU Compute,2737702132

9619